server:
  port: 9901

eureka:
  instance:
    preferIpAddress: true
    instance-id: javartisan-goods:9901
  client:
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/

spring:
  application:
    name: server-service
  cloud:
    loadbalancer:
      retry:
        enabled: false
