server:
  port: 9901

eureka:
  instance:
    preferIpAddress: true
    instance-id: GoodApi
  client:
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/

spring:
  application:
    name: good-service-app
  cloud:
    loadbalancer:
      retry:
        enabled: false
